---
all:
  hosts: 
    cvaas: 
      ansible_host: www.cv-prod-us-central1-c.arista.io
      ansible_user: cvaas
      ansible_password: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjcyMzEyODYwODY2NTAxODU2NDcsImRzbiI6InBhdGhmaW5kZXItMTctbmV3IiwiZHN0IjoiYWNjb3VudCIsImV4cCI6MTcyOTk0MDg0NiwiaWF0IjoxNzI3OTUzNjUwLCJvZ2kiOjcyMzEyODYwODY2NTAxNzQxMTgsIm9nbiI6InBhdGhmaW5kZXItMTciLCJzaWQiOiI1NmYwOTFiOThlY2MyMDg5ZGRiMzY1YTc2N2RlMGQ1MTVmNTYzOGYzZDcxYjEwYjU2ZDE4NGM5MTJjMmE1YWJiLWdldXpXb2UyczZSSFZKVjJxeVk4UHBGQ2FMU05yYU9RalgtdUYyVlkifQ.dcbV4LLOBBTsZKCpzqBPBcJ8ev7PlBwUglL1r4mbh10WxdpqaqFFgSn9il1uSf981lTnpc9iRUFjiIIj_lAjFA"
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
      ansible_network_os: eos
      ansible_httpapi_port: 443
    # cvaas: 
    #   ansible_host: 192.168.0.5
    #   ansible_user: arista
    #   ansible_password: aristajqzo
    #   ansible_connection: httpapi
    #   ansible_httpapi_use_ssl: True
    #   ansible_httpapi_validate_certs: False
    #   ansible_network_os: eos
    #   ansible_httpapi_port: 443
  children:
    PF_NETWORK:
      children:
        pathfinder:
          hosts:
            RR1:
            RR2:
            RR3:
            RR4:
        REGIONS:
          children:
            REGION1:
              children:
                REGION1-EDGE:
                  children:
                    SITE11:
                      hosts:
                        Edge10:
                    SITE12:
                      hosts: 
                        Edge12:
                    SITE13:
                      hosts:
                        Edge13:
                    SITE14:
                      hosts:
                        Edge14:
                    REGION1-TRANSIT:
                      hosts:
                        P10:
                        P11:
            REGION2:
              children:
                REGION2-EDGE:
                  children:
                    SITE21:
                      hosts:
                        Edge20:
                    SITE22:
                      hosts: 
                        Edge22:
                    SITE23:
                      hosts:
                        Edge23:
                    SITE24:
                      hosts:
                        Edge24:
                    REGION2-TRANSIT:
                      hosts:
                        P20:
                        P21: